### ISSUE TITLE
@dedupeTracked for getters?

### ISSUE THREAD

**Issue by lstrzebinczyk** [pzuraq/tracked-toolbox#14]
Hi!

Looks like tracked-toolbox will allow me to introduce some serious cleanup into otherwise very messy logic. I have a case where a critical method does this:

```
  get progress() {
    return Math.round(100 * this.args.currentTime / this.args.duration);
  }
```

These numbers are taken from a film, so duration might be in hours, and current time might be in very small numbers. Basically, this might return the same result for a lot of time, and since this goes into the template, if it updates 60 times per second with the same value, it's a whole lot of unnecessary rerenders (and style recalculations in my case).

what I would love is a decorator which I might put in front of that method, that would prevent it from triggering view rerender unless it returns a new, different value. I thought `@dedupeTracked` would be it, but it doesn't work on a getter. Can that be done with a combination of existing decorators, or maybe can a new one be added easily enough?

**Comment by jkeen** [comment]
I'm in the same boat, and I initially thought after the talk @pzuraq and I had about this issue long ago on discord that `@cached` was the answer for this? But it does not seem to make a difference when applying to the following critical logic in my app: 

```javascript
// clock service
  @tracked time = new Date()
  constructor() {
    this.poll.addPoll({
      interval: 1000,
      callback: () => {
        this.date = new Date()
      }
    });
  }

```

```javascript
  get isFuture() {
    return this.clock.time < this.args.airing.startsAt;
  }

  get isPast() {
    return this.clock.time > this.args.airing.endsAt;
  }

  get isLive() {
    return this.clock.time <= this.args.airing.endsAt && this.clock.time >= this.args.airing.startsAt;
  }

  // @cached ??
  get listMessages() {
    let messages = []

    if (this.isPast) {
       messages.push('past prompt')
    }
    else if (this.isFuture) {
      messages.push('future message')
    }
    else if (this.isLive) {
      messages.push('live prompt')
    }

   // other message additions

   return messages;
  }

```

```hbs
{{#animated-each this.listMessages use=this.transition as |message|}}
 // render message
{{/animated-each}}

```

With this setup, listMessages gets called every second, and each time it gets called the list of items re-animates the unchanged data.It seems like a dedupeTracked for a getter like @lstrzebinczyk is suggesting would fix this? I've tried the other available methods and can't seem to get around this problem

**Comment by lstrzebinczyk** [comment]
My problem was that I need to re-render parts of the app alongside a playing video. `video.currentTime` gets update extremely frequently, and if I were to rerender each time with `video.currentTime`, it would kill the performance. So I did this:

1) I pass `video.currentTime` to component
2) I `{{did-update this.updateProgress @currentTime}}`

where: 
```
  // Will produce unique value every 0.5% of progress
  @action updateProgress() {
    this.progress = Math.round(200 * this.args.currentTime / this.args.duration) / 2;
  }
```

and

```
  @dedupeTracked progress = 0;
```

This is not an ideal solution in terms of beauty, but it works well.

**Comment by pzuraq** [comment]
@lstrzebinczyk I'd like to better understand your use case, because getters rerunning shouldn't actually cause DOM updates/rerenders all on their own. Before we change anything in the DOM, we always do a last level `===` check to see if the value actually changed. If it did not, we do not change anything.

This technique is strong caching, as opposed to weak caching, which is what autotracking is about. With weak caching, you rerun your code every time something _may_ have changed, not when it definitely did change. `@cached` is a weak cache, not a strong one, so it cannot know that it shouldn't rerun when one of the values it used _possibly_ changed.

I've been thinking about ways to stop propagation if an intermediate value ends up being the same as the previous value. It's tricky, and would require integration all the way down in the autotracking primitives, and I'm still not sure it would work, but I'll keep thinking on it.

@jkeen for your use case, can you add more of the code potentially? I'd also like to understand more about it, it seems like a getter is actually kind of an awkward way to construct this list of messages. I'm wondering if there may be a better abstraction. Additionally, this will force your app to rerender every second, even if nothing has actually changed - even if we could somehow stop propagation.

**Comment by lstrzebinczyk** [comment]
In our business, we allow users to annotate films with tags, and to review them easily, we allow reviewing films in very customized way. Take a look at this:
![Firefox_Screenshot_2020-09-29T14-57-06 198Z](https://user-images.githubusercontent.com/1272828/94575723-d486d480-0274-11eb-975d-475e41255b0b.png)

In red I marked our custom video navigation, and part of the navigation is film progress bar. Currently, the process to keep it synced with the film looks like this:

1) Every once in a while we do whot boils down to:
```
this.videoCurrentTime = videoElement.currentTime
```

Well, the rest was actually described above, so the image is the addition here. 
I'd like to notice that I currently have a process that works and is relatively simple with `@dedupeTracked`, so thank you for that.

I could notice 2 levels of improvement: if there was `@dedupeGet` and I could just do 
```
@dedupe get progress() {
  return Math.round(200 * this.args.currentTime / this.args.duration) / 2;
}
```

It would remove the roundtrip through the template, and would simplify things nicely.
Even best would be to have a getter track changes of `currentTime` inside actual `<video>` tag, but I've been assuming that this will not be possible. It would be pretty awesome if it was possible, though.

**Comment by pzuraq** [comment]
@lstrzebinczyk the issue is that it is actually _impossible_ to make `@dedupe get progress` work. Tracking basically works like this:

```js
function render() {
  // Start rendering process

  // Access the getter
  this.progress;

  // Continue rendering process
}
```

We first learn that `progress` has changed in the _middle_ of rendering. We cannot cancel rendering at this point, because it has already begun.

This is why we always do a `===` comparison before we actually place a value in the DOM, so that we don't do any unnecessary work.

```js
function render() {
  // Start rendering process

  // Access the getter
  let progress = this.progress;
 
  // Check to see if progress has changed
  if (progress !== lastProgress) {
    lastProgress = progress;
    this.updateStyle(progress);
  }

  // Continue rendering process
}
```

**Comment by lstrzebinczyk** [comment]
> impossible to make @dedupe get progress work.

I can take that as a resolution for the issue. Using @dedupeTracked gives me enough power to express what I need, so I'm good.
If you'd like to learn more about what I do to learn if we can make ember/glimmer better, I'll happily work with you, but you're gonna gave to ask more specific questions, I believe I explained what we do rather fully.

**Comment by pzuraq** [comment]
So what's confusing to me at this point is, why does it matter that `progress` reruns all the time? Like I mentioned before, Ember _does_ do a check before it inserts `progress` into the template. If it's the same value, then it does nothing. Running the getter itself should be as expensive as caching the value.

So what else is `progress` doing that's causing your app to be slow, and causing you to need to use `@dedupeTracked`?

**Comment by lstrzebinczyk** [comment]
Progress specifically is problematic for me, because it's implemented as svg, with this:

```
        <rect
          width="{{this.progress}}%"
          height="100%"
          fill="rgba(255,255,255, 0.85)"
          stroke="none"
        />
```

And therefore each progress update is forcing style recalculation on a portion of the page, which adds up to a considerable overhead. Before you say I should use <progress>, I know it's an option, but it comes with it's own set of challanges.

**Comment by pzuraq** [comment]
> Before you say I should use , I know it's an option, but it comes with it's own set of challanges.

I think maybe you missed a word there?

But anyways, this is what I'm getting at - that should not be causing _any_ style recalculation. Effectively, Ember _should_ be reading `{{this.progress}}`, seeing it is the same, and doing absolutely nothing.

If that is the expensive part, then I'd like to see if we can make it cheaper, because that should be a very cheap operation if that's the only change. But if you are _actually_ seeing style changes and reflows, etc. then that is a bug in Ember/Glimmer IMO, and we need to solve that.

**Comment by lstrzebinczyk** [comment]
Looks like I messed up and didn't add proper markup. I meant I might use `<progress>`.
Anyway, that seems to be a very interesting case. I'll prepare a reproduction repository. Either I find some issue in my code which I was not aware of, or we find a bug in ember and make it better for everyone: win-win ^^. I believe I'll have it up this week, will notify you here.

**Comment by lstrzebinczyk** [comment]
@pzuraq So here is the film presenting the issue in brand new ember app:

![EmberStyleRecalculationIssue](https://user-images.githubusercontent.com/1272828/94681691-2aff1c00-0324-11eb-88ed-3e0c2c1b1c77.gif)

Pardon the weird format, github doesn't like webms, so I converted to gif with online tools; D
This is tested on chrome with "flash rerenders" option on. You can see that the svg-based progress bar is being rerendered all the time, instead only when data changes.

Here is the repo: https://github.com/lstrzebinczyk/ember-style-recalculation-issue

Brand new ember app with the issue, you can just start the app and go to localhost.

**Comment by lstrzebinczyk** [comment]
It's been quite a while now, since this was relevant to me, and there has been several ember versions since  this. I'm closing the issue.

**Comment by Techn1x** [comment]
Hi! I just wanted to present a use-case for a deduped getter. For some context, I am using trackedFunctions from NullVoxPopuli's https://github.com/universal-ember/reactiveweb

I've given thought to use of the various cache primitives and can't figure out a way to do this. If there is a way I can do this without a deduped getter, keen to hear it... even if it's messy... I'm a bit stumped

```js
/*
Returns an array like
[
  { lesson: 1, activity: 1, manifestPath: '/lessons/1' },
  { lesson: 1, activity: 2, manifestPath: '/lessons/1' },
  { lesson: 1, activity: 3, manifestPath: '/lessons/1' },
  { lesson: 2, activity: 1, manifestPath: '/lessons/2' },
  ...
]
*/
sequenceItems = trackedFunction(this, async () => {
  return fetch(...) 
})

@tracked sequenceIndex = 0 // user selects which activity to go to, which updates this value

// I want this deduped. sequenceIndex can change to 1, and the return value for this getter will still be `/lessons/1` for example.
get sequenceItemPath() {
 return this.sequenceItem.value?.[this.sequenceIndex]?.manifestPath
}

// I don't want this to re-run if sequenceItemPath is the same value^
manifestBundle = trackedFunction(this, async () => {
  // expensive operation
  return await fetch(this.sequenceItemPath)
})
```

**Comment by Techn1x** [comment]
> the issue is that it is actually impossible to make @dedupe get progress work

yeah, understood. I've enquired about this elsewhere and it seems like Starbeam might provide some possibilities to do this via `on.sync`, but that'll be a ways off.

Guess I'll have to do some refactoring :)
